### ISSUE TITLE
failed to load zaupshop

### ISSUE THREAD

**Issue by ZeroH3art** [sharkbound/ZaupShopUpdated#1]
failed to load zaupshop, unloading now... :system.io.filenotfoundexception: could not load file or assembly 'i18n.west, version=2.0.0.0, culture=neutral, publickeytoken=0738eb9f132ed756' or one of its dependencies. file name: 'i18n.west

Hello do you have any suggestion to this error?

**Comment by sharkbound** [comment]
download these two files from https://github.com/sharkbound/ZaupShopUpdated/tree/master/ZaupShop/lib/sql 

![files](https://i.imgur.com/gLavTLt.png)

add _zaupshop to the end of the file names for both (to avoid name collisions)

ex: `I18N.West_zaupshop.dll`

then add both those files to the server's rocket libraries folder (located at `steamapps\common\Unturned\Servers\SERVER NAME\Rocket\Libraries`, relative to the server's steamcmd directory)

this should make it load and function

**Comment by sharkbound** [comment]
i am marking this as closed for now, LMK if that works

**Comment by ZeroH3art** [comment]
Sure thing let me go ahead and try it thanks slot

**Comment by ZeroH3art** [comment]
[Error] Could not find dependency: I18N, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
[6/13/2020 4:14:54 AM] [Error] Could not find dependency: I18N, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
[6/13/2020 4:14:54 AM] [Error] Failed to load ZaupShop, unloading now... :System.TypeLoadException: Could not find method due to a type load error
  at ZaupShop.ZaupShop.Load () [0x00006] in <e89cfd0b775f49f98a8f5c2d1fb71bd3>:0 
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00033] in <466fa14d466749559a64a11ae8acbc60>:0 
[6/13/2020 4:14:54 AM] [Info] 
[unloading] ZaupShop


Still getting this error

**Comment by ZeroH3art** [comment]
![Error](https://user-images.githubusercontent.com/66833259/84565336-03148a00-ad2e-11ea-83cb-142ab1eb2b0d.PNG)

**Comment by sharkbound** [comment]
this is using the zaupshop dll in the release correct?

**Comment by ZeroH3art** [comment]
Correct

**Comment by sharkbound** [comment]
i can try uploading a new build to releases, doupt its the issue, but worth a  shot

**Comment by sharkbound** [comment]
i updated the release with a fresh recompile, try it out: https://github.com/sharkbound/ZaupShopUpdated/releases/tag/1.0
